server:
  port: 8000

spring:
  jpa:
    show-sql: true
    database: postgresql
#    hibernate:
#      ddl-auto: update
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _LOG
      hibernate:
        jdbc.batch_size: 20
        cache:
          use_query_cache: false
          use_second_level_cache: false
          use_structured_entries: false
          use_minimal_puts: false
        format_sql: true
#        default_schema: public
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DATASOURCE_URL}
#    url: jdbc:postgresql://127.0.0.1:5432/evg?user=evguser&password=evgpwd
    username: evguser
    password: evgpwd
    driverClassName: org.postgresql.Driver
#    continue-on-error: : true
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 150000
      max-lifetime: 300000
      connection-timeout: 5000
      register-mbeans: true
  transaction:
    default-timeout: 200



