@startuml
'https://plantuml.com/sequence-diagram

actor User
participant "Api gateway"
participant "Auth service"
participant "Otus Service"

User -> "Api gateway" : Запрос

"Api gateway" -> "Auth service" : Запрос авторизации
activate "Api gateway"

alt #LawnGreen "Пользователь авторизован"

"Auth service" -> "Api gateway" : Авторизован - 200
"Api gateway" -> "Otus Service" : Запрос с заголовками из авторизации
"Otus Service" -> "User" : Ответ

else #Orange "Пользователь не авторизован"

"Auth service" -> "Api gateway" : Не авторизован - 401
"Api gateway" -> User : Не авторизован - 401

end

deactivate "Api gateway"

@enduml