apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
data:
  DATABASE_URI: amRiYzpwb3N0Z3Jlc3FsOi8vZXZncG9zdGdyZXNkYi1wb3N0Z3Jlc3FsOjU0MzIvZXZnP3VzZXI9ZXZndXNlciZwYXNzd29yZD1ldmdwd2Q=
  DATABASE_PASSWORD: ZXZncHdk
  DATABASE_USER: ZXZndXNlcg==