apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otus
  annotations:
#    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: otus
                ports:
                  name: http
    - host: arch.homework
      http:
        paths:
          - path: /otusapp/Evgeniya(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: otus
                ports:
                  name: http