apiVersion: v1
kind: Secret
metadata:
  name: otus-secret
type: Opaque
data:
  DATABASE_URI: cG9zdGdyZXM6Ly9ldmd1c2VyOmV2Z3B3ZEBldmdwb3N0Z3Jlc2RiLXBvc3RncmVzcWwvZXZn
  DATABASE_PASSWORD: ZXZncHdk
  DATABASE_USER: ZXZndXNlcg==